name: Run checks
# Temporarily disable due to https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/94
# on:
#   pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Build project
        uses: gradle/gradle-build-action@v2.11.0
        with:
          arguments: build
      - name: Run Android lint
        uses: gradle/gradle-build-action@v2.11.0
        with:
          arguments: lintDebug
